---
conf:

  dialects:
    - name: mysql
      paginationQueryTemplate: >
        {{ query }} limit {{ uri.pageSize()*(uri.pageNumber()-1) }}, {{ uri.pageSize() }}

  endpoints:
    - name: demodb
      confDir: /sql-boot/sql
      properties:
        jdbc_url: jdbc:mysql://test-db-server:3306/mysql
        db_user: root
        db_password: password
        sql_dialect: mysql
        jdbc_driver_class_name: com.mysql.cj.jdbc.Driver

server:
     port: 8007
