version: '3'
services:

  test-db-server:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password

  sql-boot:
    build: . 
    image: sql-boot-mysql
    ports:
      - "8007:8007"
    volumes:
      - ./sql:/sql-boot/sql
      - ./application.yml:/sql-boot/application.yml

